# Generated by Django 4.2.2 on 2023-07-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
